### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by tarekbecker** [tkpraktikum/tkpraktikum#43]
Consolidation of #14 #15 #24 #28

**Must**
- [x] view profile GMap #44
- [x] view profile show name instead of username #44
- [x] GMaps ignores street #44
- [x] Submission overview info if empty #45
- [x] Registration Uppercase, Login lowercase #45 (username is changed to lower)
- [x] remove: You're Attendee #45
- [x] My Reviews overview info if empty #45
- [x] My Conference info if empty #45
- [x] useful redirect after login (is default conference --> conference landing page) #45
- [x] conference landing page: add button manage conference (edit) #45
- [x] registration doesn't set first / lastname #45
- [x] join conferences throws an error (new user, no conferences) #45 
- [x] conference landing respect phase #45
- [x] ensure logical order of submission / review phase #46 
- [x] display deadlines to user #47 
- [x] my conferenec manage users button doesn't work #47 
- [x] my conference pick conference #47 
- [x] remove seperator in nav dropdown for users with no confs #47 
- [x] edit Profil needs always affiliation to be set (seems to be fixed)
- [x] drop down needs refresh to recognize joined conferences #48
- [x] save changes (assign reviewer) show success #48
- [x] delete account #48
- [x] submission status: draft, submitted, accepted, rejected #48 (Rejected status is implicit [=> not accepted means it is rejected])
- [x] statistics
- [x] chair removes submission
- [x] social login (implement or remove)
- [ ] remove double dropdown for mobile in navigation

**Abstract**
- [ ] consider using `btn-default` instead of too much red by `btn-primary`
- [ ] try to harmonize column width
- [ ] test mobile!
- [ ] test all forms

**Nice**
- [ ] Chat
- [ ] minify and packaging
- [ ] remove fancy flips from user
- [ ] password strength
- [ ] change pw needs old pw
- [ ] delete pw needs old pw #48 (It now requires the user to enter its username for confirmation)
- [ ] user management apply filter to name only

**Comment by schnz** [comment]
Aus #48

Weitere TODO's:
- [x] After changing conference options -> redirect to conference home page instead of conference listings.
- [x] Conference name instead of "Team Whiskey" as brand in navbar (only if conference is selected)
- [x] Menüpunkte besser beschreiben, z.B. SHOW submissions, EDIT conference, ...
- [x] remove console.log() calls!
- [x] Deadlines im Header anzeigen! (Oderirgendwo anders im layout. Ggf. farbig markieren, je nachdem ob abgelaufen oder nicht)
- [x] Reload state after changing deadlines
- [x] /submission/list -> column width fix (col-md-10!)
- [x] .table-responsive class does not work well with ui-select! (admin/reviews/assignment)
- [x] Use permission permission-only="'AUTHOR'" instead of ng-show="u.isAuthor" (not fixed, only used on one page anyways)
- [x] Logout seems to lead (in some cases?) to requests of authentication required services (when redirected to login page) (not reproducable)
- [x]  .card-columns css class does not work in FF at all (simple use bootstrap column wrapping, add margin-bottom to the panels)
- [x] Add status labels of submission to chair submission overview
- [x] In conference review listing: Display author of the review (to distinguish between multiple reviewers)
- [ ] Badges im menü (anzahl d. unapproved submissions/reviews)
- [x] Titles for pages? (Or breadcrumb?)
- [ ] Update user doc & screenshoots with last minute changes (UI)
